spring:
  config:
    activate:
      on-profile: google-v2

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.client.id}
            client-secret: ${google.client.secret}
            scope: profile, email, openid
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            authorization-grant-type: authorization_code

        provider:
          google:
            issuer-uri: https://accounts.google.com
server:
  port: 8080
