version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-oauth
    environment:
      POSTGRES_USER: oauth2
      POSTGRES_PASSWORD: password
      POSTGRES_DB: oauth2db
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis-oauth
    ports:
      - "6379:6379"
    restart: unless-stopped
